name: newsapp
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Custom Fonts
  fonts:
    - family: Blinker
      fonts:
        - asset: assets/fonts/Blinker-Bold.ttf
        - asset: assets/fonts/Blinker-Regular.ttf
        - asset: assets/fonts/Blinker-SemiBold.ttf
          style: italic
